fix danted not start if host disable ipv6
Hagb/docker-easyconnect pull request #145
Opened 2022-05-04 18:51 UTC by redjumper

[#140](https://github.com/Hagb/docker-easyconnect/issues/140) fix danted not start if host disable ipv6
also made some changes to danted conf

2022-05-06 12:18 UTC, Hagb requested changes

2022-05-06 12:18 UTC, Hagb commented on docker-root/etc/danted.conf.sample
> +internal: eth0 port = 1080
容器出口的网络接口不一定会是 `eth0`，如 podman 下可能是 `tap`: https://github.com/Hagb/docker-easyconnect/issues/75 ，此处可以保持原来的处理方式（或者也欢迎其他可行的处理方式）
严格意义上来说，或许我们不应该假定出口的网络接口名

2022-05-06 12:18 UTC, Hagb commented on docker-root/etc/danted.conf.sample
> +        from: 0.0.0.0/0 to: 0.0.0.0/0
这里回将 ipv6 的客户端排除 https://github.com/Hagb/docker-easyconnect/issues/74 ，保持 `0/0` 可以兼容仅 ipv4 的情形

2022-05-06 12:18 UTC, Hagb commented on docker-root/etc/danted.conf.sample
> +        from: 0.0.0.0/0 to: 0.0.0.0/0
同上
```suggestion
        from: 0.0.0.0/0 to: 0.0.0.0/0
```
```suggestion
        from:0/0 to: 0/0
```

2022-05-06 12:18 UTC, Hagb commented on docker-root/etc/danted.conf.sample
> +        from: 0.0.0.0/0 to: 0.0.0.0/0
同上
```suggestion
        from: 0.0.0.0/0 to: 0.0.0.0/0
```
```suggestion
        from:0/0 to: 0/0
```

2022-05-06 12:18 UTC, Hagb commented on docker-root/etc/danted.conf.sample
> +        from: 0.0.0.0/0 to: 0.0.0.0/0
这里会将 ipv6 的客户端排除 https://github.com/Hagb/docker-easyconnect/issues/74 ，保持 `0/0` 可以兼容仅 ipv4 的情形
```suggestion
        from: 0/0 to: 0/0
```

2022-05-06 12:18 UTC, Hagb commented on docker-root/etc/danted.conf.sample
> +        from: 0.0.0.0/0 to: 0.0.0.0/0
这里会将 ipv6 的客户端排除 https://github.com/Hagb/docker-easyconnect/issues/74 ，保持 `0/0` 可以兼容仅 ipv4 的情形
```suggestion
        from: 0/0 to: 0/0
```
```suggestion
        from: 0/0 to: 0/0
```

2022-07-19 12:21 UTC, redjumper commented on docker-root/etc/danted.conf.sample
> +internal: eth0 port = 1080
没考虑到这种情况，已经对应处理，还是用接口名

2022-07-19 12:21 UTC, redjumper commented on docker-root/etc/danted.conf.sample
> +        from: 0.0.0.0/0 to: 0.0.0.0/0
已改

2022-07-22 22:46 UTC, Hagb requested changes

2022-07-22 22:46 UTC, Hagb commented on docker-root/usr/local/bin/start.sh
> +sed /^internal/c"$internals" -i /run/danted.conf
这样其实和先前的行为不太一样了，先前在 `externals` 中加入所有网卡，是考虑到除了经过代理的 ip 外，其他未经代理的 ip 同时亦可访问到，如果去掉 externals 的生成，结果会是仅仅可以访问到经过代理的 ip（如果有兴趣的话也可以再开一个 PR 开提供一个开关让用户指定此处的行为）。
https://github.com/Hagb/docker-easyconnect/issues/140#issuecomment-1113702709 中回复了一种方式或许会有一些参考作用。

2022-07-22 22:46 UTC, Hagb commented on docker-root/usr/local/bin/start.sh
> +	/usr/sbin/danted -f /run/danted.conf
先前将 danted 放在 daemon 用户下运行是为了消除 danted 用 root 用户运行时的警告（另外理论上确实也更安全），此处的改动是否有什么原因？
```suggestion
	su daemon -s /usr/sbin/danted -f /run/danted.conf
```

2022-07-23 05:12 UTC, redjumper commented on docker-root/usr/local/bin/start.sh
> +sed /^internal/c"$internals" -i /run/danted.conf
的确，考虑不周，chrome设置能按规则连接，而ie只能全局，还是按以前方式处理吧。访问普通的网站多一跳也没什么关系，提供一个开关让用户指定此处的行为可能意义不是很大，暂时不另开PR了。

2022-07-23 05:28 UTC, redjumper commented on docker-root/usr/local/bin/start.sh
> +	/usr/sbin/danted -f /run/danted.conf
这里可能不能依赖daemon用户，或许有些发行系都没有daemon用户
PR中添加了socks用户，danted运行在socks用户下
Dockerfile 
`RUN groupadd -r socks && useradd -r -g socks socks`
danted.conf
`user.notprivileged: socks`
PS:danted.conf套用了官方的完整最小模板，和原先的差异大概就是日志了，其他应该没有什么改变
PR的代码已打包测试过

2022-08-05 18:20 UTC, merged

2022-08-05 18:20 UTC, Hagb commented
感谢PR，squash merge 了

2024-05-10 11:49 UTC, Hagb commented on docker-root/usr/local/bin/start.sh
> +        externals="${externals}external: $iface\\n"
请问此处排除了 `lo` 、`sit`、`vir` 是出于什么考虑？后两者是因为可能没有地址从而 bind 不上吗？
https://github.com/docker-easyconnect/docker-easyconnect/issues/339 可能需要将 `lo` 也加入监听范围。

2024-05-13 03:05 UTC, redjumper commented on docker-root/usr/local/bin/start.sh
> +        externals="${externals}external: $iface\\n"
的确，pasta模式下如果容器只对本机暴露端口，那么lo也要加入监听范围。至于sit、vir，这两个不会被普通的服务使用

2024-05-14 02:36 UTC, redjumper commented on docker-root/usr/local/bin/start.sh
> +        externals="${externals}external: $iface\\n"
直接监听0.0.0.0 可能更好，就像 nginx 和 tinyproxy 一样
需要测试https://github.com/docker-easyconnect/docker-easyconnect/issues/339#issuecomment-2109160784

2024-05-14 03:11 UTC, redjumper commented on docker-root/usr/local/bin/start.sh
> +        externals="${externals}external: $iface\\n"
还是直接监听0.0.0.0 ::比较简单些，就像nginx、tinyproxy一样
ipv6禁用的情况单独判断
另外需要测试