Add easy-novnc as novnc server
Hagb/docker-easyconnect pull request #161
Opened 2022-07-20 02:56 UTC by mac-zhou

添加easy-novnc 实现web端图形界面登录

#47

2022-07-20 03:55 UTC, Hagb requested changes

2022-07-20 03:55 UTC, Hagb commented on docker-root/usr/local/bin/start.sh
> +fi
这段可能适合加在上面 `if [ "$TYPE" != "X11" -a "$TYPE" != "x11" ]` 下，因为不使用 VNC 时不需要 novnc.
此外，前面 Dockerfile 中的 `ENV NOVNC_PORT=5901` 可以改到此处 `easy-novnc` 前：`ENV NOVNC_PORT=5901 easy-novnc 2>/dev/null &`

2022-07-20 03:55 UTC, Hagb commented on Dockerfile
> +ENV NOVNC_PORT=5901
这个端口不需要（也不能）开放给用户修改，所以我认为最好直接加在脚本里（见下面的 review）

2022-07-20 03:55 UTC, Hagb commented on doc/usage.md
> +
最好还请再在下面的服务说明提一下 novnc 服务

2022-07-20 04:04 UTC, Hagb commented
感谢 PR! 

先前 https://github.com/Hagb/docker-easyconnect/issues/47#issuecomment-1189448697 里
> 之前支持其他非 x86 架构的尝试让事情稍微复杂了些

所说的事情复杂了是指 easy-novnc 只提供了 3 个架构的 binary，如果要考虑多种不同架构的话可能就需要编译，不过现在 master 分支目前也只是考虑了 amd64（其实 i386 仅需替换一下下载地址也就可以）

2022-07-20 06:54 UTC, mac-zhou commented on Dockerfile
> +ENV NOVNC_PORT=5901
如果不开放的修改的话，那直接带-p 参数启动

2022-07-20 06:54 UTC, mac-zhou commented on docker-root/usr/local/bin/start.sh
> +fi
😄 抱歉 没考虑到

2022-07-20 07:13 UTC, mac-zhou commented on doc/usage.md
> +
已添加

2022-07-21 02:14 UTC, Hagb commented on doc/usage.md
> +- `NOVNC`: 默认为空，不为空时将启动easy-novnc，端口为8080， 可用-p参数转发。
刚才准备合并感觉这个变量名有点点迷惑性，或许可以改成类似于 `USENOVNC` 之类的（供参考，别的名字也可以）（因为"novnc" 的双重含义，特别是前面还有个 `NODANTED` 的参数，不看文档的话可能容易让人联想成不开 VNC 服务？）

2022-07-22 06:04 UTC, mac-zhou commented on doc/usage.md
> +- `NOVNC`: 默认为空，不为空时将启动easy-novnc，端口为8080， 可用-p参数转发。
确实有些迷惑 已改名为 USE_NOVNC

2022-07-22 23:05 UTC, Hagb approved these changes

2022-07-23 00:04 UTC, merged