添加中文字体 && 退出不自动重启参数补充
Hagb/docker-easyconnect pull request #199
Opened 2022-12-07 14:16 UTC by dhy2000

## 添加中文字体

由于 docker 内没有中文字体，中文汉字在 vnc 和 x11 中可能显示为方块或乱码，在图形界面的 Dockerfile 中安装 `fonts-wqy-microhei` 字体以解决中文显示问题。

## 退出不自动重启

经过本地实测，[usage 文档](https://github.com/Hagb/docker-easyconnect/blob/master/doc/usage.md) 中给出的命令示例仅包含 `EXIT=1` 环境变量，退出 easyconnect 图形界面仍然会重新连接，需要加上 `MAX_RETRY=0` 才真正实现退出不重连。

2023-01-17 15:13 UTC, Hagb commented
感谢PR！

> 退出不自动重启，与 `EXIT` 环境变量相关的逻辑在 [start.sh 第 60 行](https://github.com/Hagb/docker-easyconnect/blob/master/docker-root/usr/local/bin/start.sh#L60) 中出现，根据该行代码推断需要补充 `MAX_RETRY=0` 并实测有效。

感谢反馈。这里提到的那行代码确实有 bug（https://github.com/Hagb/docker-easyconnect/issues/180#issuecomment-1273981513 ）：

https://github.com/Hagb/docker-easyconnect/blob/63abcac18ad463e365b1dbd05c5e944dbcc88386/docker-root/usr/local/bin/start.sh#L60

改为

```bash
[ -n "$EXIT" ] && export MAX_RETRY=0
```

可修复 `EXIT` 变量无效的问题

2023-01-17 15:16 UTC, Hagb requested changes

2023-01-17 15:16 UTC, Hagb commented on Dockerfile.vncless
> +RUN cd tmp && apt-get download x11-utils && dpkg -x x11-utils_*.deb x11-utils &&\
```suggestion
RUN cd tmp && apt-get update && apt-get download x11-utils && dpkg -x x11-utils_*.deb x11-utils &&\
```
此处再次 `update` 的目的是防止复用前面的构建步骤时 apt 本地缓存已经过期

2023-01-17 15:16 UTC, Hagb commented on Dockerfile.vncless
> +RUN apt-get install fonts-wqy-microhei
此处最好放在前一个 `RUN` 语句的 `apt-get install` 中

2023-01-17 15:16 UTC, Hagb commented on Dockerfile
> +RUN apt-get install fonts-wqy-microhei
此处最好放在前一个 `RUN` 语句的 `apt-get install` 中

2023-01-18 04:53 UTC, dhy2000 commented on Dockerfile.vncless
> +RUN cd tmp && apt-get download x11-utils && dpkg -x x11-utils_*.deb x11-utils &&\
已在 4d3daa6dbd7b310cf31c83651a407dc3d0ce396d 中修改，感谢！

2023-01-18 04:53 UTC, dhy2000 commented on Dockerfile.vncless
> +RUN apt-get install fonts-wqy-microhei
已在 4d3daa6dbd7b310cf31c83651a407dc3d0ce396d 中修改，感谢！

2023-01-18 04:53 UTC, dhy2000 commented on Dockerfile
> +RUN apt-get install fonts-wqy-microhei
已在 4d3daa6dbd7b310cf31c83651a407dc3d0ce396d 中修改，感谢！

2023-01-18 04:54 UTC, dhy2000 commented
Requested changes 已在 4d3daa6dbd7b310cf31c83651a407dc3d0ce396d 中修改，感谢作者！

2023-01-18 06:45 UTC, Hagb requested changes

2023-01-18 06:45 UTC, Hagb commented on doc/usage.md
> +docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -v $HOME/.easyconn:/root/.easyconn -e EC_VER=7.6.3 -e EXIT=1 -e MAX_RETRY=0 -p 127.0.0.1:1080:1080 hagb/docker-easyconnect:cli
```suggestion
docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -v $HOME/.easyconn:/root/.easyconn -e EC_VER=7.6.3 -e EXIT=1 -p 127.0.0.1:1080:1080 hagb/docker-easyconnect:cli
```
此处可以不加 `MAX_RETRY=0` 了

2023-01-18 06:45 UTC, Hagb commented on doc/usage.md
> +docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/.Xauthority:/root/.Xauthority -e EXIT=1 -e MAX_RETRY=0 -e DISPLAY=$DISPLAY -e URLWIN=1 -e TYPE=x11 -
```suggestion
docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/.Xauthority:/root/.Xauthority -e EXIT=1 -e DISPLAY=$DISPLAY -e URLWIN=1 -e TYPE=x11 -v $HOME/.ecdata:/root -p 127.0.0.1:1080:1080 hagb/docker-easyconnect:vncless-7.6.3
```
同上

2023-01-18 08:20 UTC, Hagb approved these changes

2023-01-18 08:26 UTC, merged