Update readme
Hagb/docker-easyconnect pull request #23
Opened 2020-12-26 10:31 UTC by chroming

更新readme; 添加macos示例脚本macos_example.sh

2020-12-26 14:00 UTC, Hagb commented
非常感谢你的文档和脚本！

2020-12-26 14:01 UTC, Hagb requested changes

2020-12-26 14:01 UTC, Hagb commented on README.md
> +1. [安装Docker并运行]（https://docs.docker.com/get-docker/）；
此处 `https://docs.docker.com/get-docker/` 可用尖括号括住（即 `<https://docs.docker.com/get-docker/>`）以防链接后的`）；`也被识别为链接的一部分。（又或许这里是不是把括号打成全角了？）

2021-01-21 10:06 UTC, Tomzhang12138 commented on macos_example.sh
> +# Then you can connect with vnc client
test

2021-02-09 12:55 UTC, merged