似乎解决了 #154 中提到的dns解析问题
Hagb/docker-easyconnect pull request #243
Opened 2023-04-08 16:35 UTC by WnPro

按照 @Hagb 大佬的方案，把相应的规则修改，新增dns的操作写在了代码里，让服务重启之后也可以正常工作。同时更新了对应的文档。#154

做了简单的测试，应该是可以用的。总之还是谢谢 @Hagb 解惑了。

2023-06-19 09:52 UTC, PaleNeutron commented
借楼问一下如果希望在外部使用容器里VPN的DNS，比如解析公司内网 xxx.inner.com。需要怎么进行操作才能把容器的5373端口变为一个dns server呢

2023-06-19 15:19 UTC, wunewww commented
> 借楼问一下如果希望在外部使用容器里VPN的DNS，比如解析公司内网 xxx.inner.com。需要怎么进行操作才能把容器的5373端口变为一个dns server呢

首先回答问题，使用仓库原来的代码（不要用PR的），根据iptables中的nat转发规则，所有去往53端口的udp流量都会被转发到`127.0.0.1:5373` ，所以你可以直接在创建容器的时候用 `-p 53:53` 直接把容器的53端口绑定到宿主机的53端口上，这样就相当于使用了容器中的dns。

由于easyconnect自建的本地dns可能没有除内网解析以外的其他解析（我学校就是这样），遂有该pr。这个pr做的是删除原来nat转发规则，新增的规则仅将发往 `127.0.0.1:53` 的流量转发到 `127.0.0.1:5373`，同时在 `/etc/resolv.conf` 中追加一条或数条记录的方式，实现外网解析（nameserver记录由创建容器时的参数指定）。

因此，不建议以上述的暴露53端口的方法使用容器的dns解析。由于http代理不会在本地进行解析，会将访问的域名一同发往代理服务器，由代理服务器进行解析。建议使用http代理，将域名解析的任务交给容器。如果需要在本地使用clash之类的软件配置其他的转发分流规则，请配置基于域名的规则，不要配置基于ip地址的规则。

2023-06-25 09:20 UTC, Hagb commented
非常抱歉，这几个月来一直在忙着做毕业论文。现在做完了才有时间来仔细看 PR。

2023-06-26 16:56 UTC, Hagb requested changes
感谢贡献！有一些地方可能需要改一下

2023-06-26 16:56 UTC, Hagb commented on docker-root/usr/local/bin/start-sangfor.sh
> +				iptables -t nat -C OUTPUT "${RULE_DELETE[@]}" 2> /dev/null && iptables -t nat -D OUTPUT "${RULE_DELETE[@]}" 2> /dev/null
修改 EasyConnect 的 iptables 操作建议通过 `docker-root/usr/sbin/xtables-echook-multi` 来进行，如：
```diff
diff --git a/docker-root/usr/sbin/xtables-echook-multi b/docker-root/usr/sbin/xtables-echook-multi
index 5f20e82..59ef547 100755
--- a/docker-root/usr/sbin/xtables-echook-multi
+++ b/docker-root/usr/sbin/xtables-echook-multi
@@ -9,6 +9,12 @@ xtables_multi="xtables-$iptables_type-multi"
 case "$name" in
 	iptables | iptables-legacy | iptables-nft )
 		[ "$*" = "-t filter -A SANGFOR_VIRTUAL -j DROP" ] && exit 0
+		if [ -n "$ADD_NAMESERVER" ]; then
+			[ "-t nat -A OUTPUT -p udp ! --sport 7789 --dport 53 -j DNAT --to-destination 127.0.0.1:5373" = "$*" ] &&
+				set -- -t nat -A OUTPUT -p udp ! --sport 7789 -d 127.0.0.1 --dport 53 -j DNAT --to-destination 127.0.0.1:5373
+			[ "-t nat -D OUTPUT -p udp ! --sport 7789 --dport 53 -j DNAT --to-destination 127.0.0.1:5373" = "$*" ] &&
+				set -- -t nat -D OUTPUT -p udp ! --sport 7789 -d 127.0.0.1 --dport 53 -j DNAT --to-destination 127.0.0.1:5373
+		fi
 		subcommand=iptables
 		;;
 	iptables-save | iptables-nft-save | iptables-legacy-save )
```

2023-06-26 16:56 UTC, Hagb commented on docker-root/usr/local/bin/start-sangfor.sh
> +				grep -qxF "nameserver $ADD_NAMESERVER" /etc/resolv.conf || echo "nameserver $ADD_NAMESERVER" >> /etc/resolv.conf
此处只有 cli 版本会执行到，建议放在
https://github.com/Hagb/docker-easyconnect/blob/0858a686ca4d3b6e8d2f90d7160ec1a62a312543/docker-root/usr/local/bin/start-sangfor.sh#L8
的前面，使用类似于下面的方式来运行
```bash
[ -n "$ADD_NAMESERVER" ] && while sleep 1; do
	grep -qxF "nameserver $ADD_NAMESERVER" /etc/resolv.conf || echo "nameserver $ADD_NAMESERVER" >> /etc/resolv.conf
done &
```

2023-06-27 08:24 UTC, wunewww commented on docker-root/usr/local/bin/start-sangfor.sh
> +				iptables -t nat -C OUTPUT "${RULE_DELETE[@]}" 2> /dev/null && iptables -t nat -D OUTPUT "${RULE_DELETE[@]}" 2> /dev/null
这样似乎会让修改 `iptables` 的操作在easyconn启动之前执行。#154 的问题在于easyconn启动之后会用一个nat转发规则劫持dns。这个操作执行的时间大致是在第23/24行启动easyconn之后**不久**。我试了试，`sleep 1` 的效果并不好，所以就写在了循环体里面。

之所以发现了这个问题是因为手动修改iptables之后，每次重启iptables都会被覆写。所以才出此下策，让重启之后也能正常使用。

2023-06-27 08:27 UTC, wunewww commented on docker-root/usr/local/bin/start-sangfor.sh
> +				grep -qxF "nameserver $ADD_NAMESERVER" /etc/resolv.conf || echo "nameserver $ADD_NAMESERVER" >> /etc/resolv.conf
其实是因为我没有试GUI的版本，不清楚GUI存不存在类似的问题/症状类似不类似。。

2023-06-27 08:42 UTC, Hagb commented on docker-root/usr/local/bin/start-sangfor.sh
> +				iptables -t nat -C OUTPUT "${RULE_DELETE[@]}" 2> /dev/null && iptables -t nat -D OUTPUT "${RULE_DELETE[@]}" 2> /dev/null
这个文件其实是截获 iptables 调用的过程，在 iptables 被调用时执行。（`/usr/sbin/iptables` 实际上被改成了指向这个文件，这是为了修改 easyconnect 的行为而做的 hack，不过我还没有把注释还没有写清楚）

2023-06-27 08:44 UTC, Hagb commented on docker-root/usr/local/bin/start-sangfor.sh
> +				grep -qxF "nameserver $ADD_NAMESERVER" /etc/resolv.conf || echo "nameserver $ADD_NAMESERVER" >> /etc/resolv.conf
> 其实是因为我没有试GUI的版本，不清楚GUI存不存在类似的问题/症状类似不类似。。

gui 版本也有一样的问题

2023-06-27 10:37 UTC, wunewww commented on docker-root/usr/local/bin/start-sangfor.sh
> +				iptables -t nat -C OUTPUT "${RULE_DELETE[@]}" 2> /dev/null && iptables -t nat -D OUTPUT "${RULE_DELETE[@]}" 2> /dev/null
嗷我看懂了，这个shell 的case语法真是蛋疼。我改一下

2023-06-27 14:29 UTC, wunewww commented
我重新研究了一下，我认为 `easyconn` 在启动时会查看 `/etc/resolv.conf` 中的域名解析地址，然后用本机地址替换。再自己启动一个再5375端口的服务，这个服务上会同时包括内网的解析地址以及原来 `/etc/resolv.conf` 中的解析地址，以实现解析正常。

我认为出现问题和docker（可能是docker on wsl）访问网络的方式有关，这个时候容器使用的nameserver是主机地址。我不太理解其中的细节，但是只需要在容器启动以后，easyconn启动之前，把一条公共dns加到 `/etc/resolv.conf` 中，easyconn 就能识别这个dns，最后正常访问外网。

另，没看懂 `kill %1 %2` 的含义，手贱改成了 `kill ($jobs -p)`。

2023-07-21 08:29 UTC, Hagb commented on docker-root/usr/local/bin/start-sangfor.sh
> +				iptables -t nat -C OUTPUT "${RULE_DELETE[@]}" 2> /dev/null && iptables -t nat -D OUTPUT "${RULE_DELETE[@]}" 2> /dev/null
是不是忘记把规则加上去了？

2023-07-21 08:40 UTC, Hagb commented on docker-root/usr/local/bin/start-sangfor.sh
> +				grep -qxF "nameserver $ADD_NAMESERVER" /etc/resolv.conf || echo "nameserver $ADD_NAMESERVER" >> /etc/resolv.conf
现在这种是在 easyconnect 启动前加入 dns 服务器，也会被 easyconnect 覆盖，可能还是需要原来的思路。
另外，我发现 docker run 的时候自带了设置 DNS 的选项 `--dns`，功能和 `ADD_NAMESERVER` 有部分重合。我觉得可以把 `ADD_NAMESERVER` 改成一个开关，开启之后会在 easyconnect 启动后把原 `/etc/resolv.conf` 的内容追加到 easyconnect 重新设置后的 `/etc/resolv.conf`。如：

```
resolv="$(cat /etc/resolv.conf)"
[ -n "$ADD_NAMESERVER" ] && while sleep 1; do
	IFS="
"
	for line in $resolv; do
		grep -qxF "$line" /etc/resolv.conf || echo "nameserver $ADD_NAMESERVER" >> /etc/resolv.conf
	done
done &
```

2023-09-09 14:38 UTC, closed without merging