Add tinyproxy to support http & https proxy
Hagb/docker-easyconnect pull request #66
Opened 2021-07-25 10:32 UTC by ztongxue

这个 PR 给纯命令行版本的镜像增加了一个 tinyproxy 代理

2021-07-29 12:41 UTC, Hagb requested changes
感谢你的 PR！其中有一些地方还麻烦修改一些。

2021-07-29 12:41 UTC, Hagb commented on README.md
> +	```
文档请在 master 分支的基础上修改

2021-07-29 12:41 UTC, Hagb commented on Dockerfile.cli
> +	dante-server busybox iproute2 tinyproxy && \
建议使用 tinyproxy-bin 包（节省约 0.5M），可以减少额外依赖

2021-07-29 12:41 UTC, Hagb commented on docker-root/usr/local/bin/start-sangfor.sh
> +		service tinyproxy restart
改用 `tinyproxy-bin` 包时可使用 `tinyproxy -c /etc/tinyproxy.conf` 来启动。此外建议 `tinyproxy` 的启动放在 [`docker-root/usr/local/bin/start.sh`](https://github.com/Hagb/docker-easyconnect/blob/master/docker-root/usr/local/bin/start.sh) 处（如在其 20 行处插入），这样可以让图形界面版本也可以使用 tinyproxy。

2021-07-29 12:49 UTC, Hagb commented on Dockerfile.cli
> +	dante-server busybox iproute2 tinyproxy && \
```suggestion
	dante-server busybox iproute2 tinyproxy-bin && \
```

2021-07-29 13:15 UTC, ztongxue commented on README.md
> +	```
直接在原 README.md 上增加内容也可以吗

2021-07-29 13:17 UTC, ztongxue commented on docker-root/usr/local/bin/start-sangfor.sh
> +		service tinyproxy restart
okk！我尽快找个时间修改并测试，没问题后我再重新提交 PR。

2021-07-29 13:22 UTC, Hagb commented on docker-root/usr/local/bin/start-sangfor.sh
> +		service tinyproxy restart
> okk！我尽快找个时间修改并测试，没问题后我再重新提交 PR。

只需在该 pr 的分支 commit 即可

2021-07-29 13:28 UTC, Hagb commented on README.md
> +	```
> 直接在原 README.md 上增加内容也可以吗

可以在 [`master`](https://github.com/Hagb/docker-easyconnect/tree/977f04ef2ef8f45805d8e0b87616b22d71bc38c0) 的 [README.md](https://github.com/Hagb/docker-easyconnect/blob/977f04ef2ef8f45805d8e0b87616b22d71bc38c0/README.md) 的例子中加上开放 tinyproxy 端口的参数和 http 代理的简单使用说明。进一步的详细介绍则请放在 [`doc/usage.md`](https://github.com/Hagb/docker-easyconnect/blob/master/doc/usage.md#服务说明) 下。

2021-08-03 10:21 UTC, ztongxue commented on docker-root/usr/local/bin/start-sangfor.sh
> +		service tinyproxy restart
这几天忙于求婚，整忘记了哈哈。刚才修改后，测试没发现什么问题，已提交。

2021-08-03 18:14 UTC, Hagb commented on docker-root/usr/local/bin/start-sangfor.sh
> +		service tinyproxy restart
啊提交不急的😂。祝你们幸福！

2021-08-03 18:30 UTC, merged